version: 2.1

orbs:
  node: circleci/node@5.1.0
  gcp-gcr: circleci/gcp-gcr@0.15.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build:backend

  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - gcp-gcr/gcr-auth

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
