version: 2.1

orbs:
  node: circleci/node@5.1.0
  gcp-gcr: circleci/gcp-gcr@0.15.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build:backend

  deploy:
    machine:
      image: ubuntu-2204:2022.10.1
      docker_layer_caching: true
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - run:
          name: Build and push image to GCP Artifact Registry
          command: | 
            export DOCKER_BUILDKIT=1
            gcloud auth configure-docker asia-northeast1-docker.pkg.dev
            docker image build -t backstage .
            docker tag backstage asia-northeast1-docker.pkg.dev/circleci-tadashi/backstage/app:${CIRCLE_SHA1}
            docker push asia-northeast1-docker.pkg.dev/circleci-tadashi/backstage/app:${CIRCLE_SHA1}

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
